apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: muninn-webhook-spc-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: muninn-webhook-spc-writer
subjects:
  - kind: ServiceAccount
    name: muninn-webhook
    namespace: muninn-system
