apiVersion: v1
kind: Service
metadata:
  name: muninn-webhook
  namespace: muninn-system
  labels:
    app: muninn-webhook
spec:
  type: ClusterIP
  selector:
    app: muninn-webhook
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
