apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: muninn-webhook
  annotations:
    cert-manager.io/inject-ca-from: muninn-system/muninn-webhook-cert
webhooks:
  - name: mutate.muninn.io
    clientConfig:
      service:
        name: muninn-webhook
        namespace: muninn-system
        path: /mutate
        port: 443
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
