{{- if eq .Values.certificate.mode "cert-manager" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: muninn-webhook-selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
