apiVersion: muninn.io/v1alpha1
kind: Policy
metadata:
  name: arasaka
  namespace: tenant-arasaka
spec:
  jwt:
    issuerAllowList:
      - "https://auth.example.com"
    subjectClaim: "sub"
    scopesClaim: "scp"
  bindings:
    - subject: "service-account:authz"
      permissions:
        - "config:read"
  roleBindings:
    - role: "admin"
      permissions:
        - "config:read"
        - "config:write"
