apiVersion: muninn.io/v1alpha1
kind: TenantConfig
metadata:
  name: arasaka
  namespace: tenant-arasaka
spec:
  runtimeConfig:
    FEATURE_FLAG_ENABLE: "true"
    MAX_CONNECTIONS: "100"
    LOG_LEVEL: "info"
