status:
  phase: Ready
  namespace: tenant-arasaka
  cloudResources:
    identityPoolID: sample-identity-pool-0000
    identityPoolARN: "arn:aws:cognito-identity:us-east-1:000000000000:identitypool/us-east-1:00000000-0000-0000-0000-000000000000"
    identityClientID: sample-client-0000
    identityDomain: arasaka.sample.auth.local
    storageBucketName: arasaka-runtime-config
    storageBucketARN: "arn:aws:s3:::arasaka-runtime-config"
